### ISSUE TITLE
Your device does not have internet access

### ISSUE THREAD

**Issue by powertalent** [EdwardLab/flyos#76]
How to fix this issue: 
"Your device does not have internet access"
My device connected to Internet
![image](https://github.com/EdwardLab/flyos/assets/9014346/fd7748a7-8925-474c-8bbe-9cf648793b14)

**Comment by EdwardLab** [comment]
Hi! If your device can connect to google.com, I think your system may doesn't build curl, this may be a flaw of FlyOS Installer. Could you please use ```adb shell curl google.com``` and return output results? If this is a bug, I will fix it
This is the expected result:
```
adb shell curl google.com
   % Total % Received % Xferd Average Speed Time Time Time Current
                                  Dload Upload Total Spent Left Speed
   0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
100 219 100 219 0 0 789 0 --:--:-- --:--:-- --:--:-- 793
```
Thank you and have a great day!

**Comment by powertalent** [comment]
Thank you for your answer.
I noticed that the 'curl' command is missing from my system.
![image](https://github.com/EdwardLab/flyos/assets/9014346/21c7abb2-a405-49d5-863b-e834438bc995)

**Comment by EdwardLab** [comment]
thanks for your reply
Well curl is missing on some Android build, use the latest version of Installer once i release, thank you!

**Comment by EdwardLab** [comment]
Fixed! Here's latest version of Installer: https://github.com/DigitalPlatDev/FlyOS-Installer/releases/tag/1.0010
If there's still have a problem, kindly report here and anyways you can use force-ignore warnings or errors, simply create an empty file named 'ignore_error' in the Installer directory and restart the Installer

**Comment by powertalent** [comment]
Thank you for new release and fix.
